name = "reseachbub"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
CF_PAGES = "true"

# SPA路由处理 - 只对HTML路由进行重定向，保留静态文件访问
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
conditions = {exclude = ["*.svg", "*.js", "*.css", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.ico", "*.json", "*.woff", "*.woff2", "*.ttf", "*.eot"]}

# 添加sitemap.xml的访问规则
[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200 