name = "reseachbub"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
CF_PAGES = "true"

# 强制HTTPS重定向 - 将所有HTTP请求重定向到HTTPS
[[redirects]]
from = "http://reseachbub.org/*"
to = "https://reseachbub.org/:splat"
status = 301
force = true

# SPA路由处理 - 只对HTML路由进行重定向，保留静态文件访问
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
conditions = {exclude = ["*.svg", "*.js", "*.css", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.ico", "*.json", "*.woff", "*.woff2", "*.ttf", "*.eot", "*.txt", "*.xml", "*.pdf"]} 